package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class DescribeLayout implements com.sforce.ws.bind.XMLizable , IDescribeLayout{

    /**
     * Constructor
     */
    public DescribeLayout() {}

    /**
     * element : buttonLayoutSection of type {urn:partner.soap.sforce.com}DescribeLayoutButtonSection
     * java type: com.sforce.soap.partner.DescribeLayoutButtonSection
     */
    private static final com.sforce.ws.bind.TypeInfo buttonLayoutSection__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","buttonLayoutSection","urn:partner.soap.sforce.com","DescribeLayoutButtonSection",0,1,true);

    private boolean buttonLayoutSection__is_set = false;

    private com.sforce.soap.partner.DescribeLayoutButtonSection buttonLayoutSection;

    @Override
    public com.sforce.soap.partner.DescribeLayoutButtonSection getButtonLayoutSection() {
      return buttonLayoutSection;
    }

    @Override
    public void setButtonLayoutSection(com.sforce.soap.partner.IDescribeLayoutButtonSection buttonLayoutSection) {
      this.buttonLayoutSection = (com.sforce.soap.partner.DescribeLayoutButtonSection)buttonLayoutSection;
      buttonLayoutSection__is_set = true;
    }

    /**
     * element : detailLayoutSections of type {urn:partner.soap.sforce.com}DescribeLayoutSection
     * java type: com.sforce.soap.partner.DescribeLayoutSection[]
     */
    private static final com.sforce.ws.bind.TypeInfo detailLayoutSections__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","detailLayoutSections","urn:partner.soap.sforce.com","DescribeLayoutSection",0,-1,true);

    private boolean detailLayoutSections__is_set = false;

    private com.sforce.soap.partner.DescribeLayoutSection[] detailLayoutSections = new com.sforce.soap.partner.DescribeLayoutSection[0];

    @Override
    public com.sforce.soap.partner.DescribeLayoutSection[] getDetailLayoutSections() {
      return detailLayoutSections;
    }

    @Override
    public void setDetailLayoutSections(com.sforce.soap.partner.IDescribeLayoutSection[] detailLayoutSections) {
      this.detailLayoutSections = castArray(com.sforce.soap.partner.DescribeLayoutSection.class, detailLayoutSections);
      detailLayoutSections__is_set = true;
    }

    /**
     * element : editLayoutSections of type {urn:partner.soap.sforce.com}DescribeLayoutSection
     * java type: com.sforce.soap.partner.DescribeLayoutSection[]
     */
    private static final com.sforce.ws.bind.TypeInfo editLayoutSections__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","editLayoutSections","urn:partner.soap.sforce.com","DescribeLayoutSection",0,-1,true);

    private boolean editLayoutSections__is_set = false;

    private com.sforce.soap.partner.DescribeLayoutSection[] editLayoutSections = new com.sforce.soap.partner.DescribeLayoutSection[0];

    @Override
    public com.sforce.soap.partner.DescribeLayoutSection[] getEditLayoutSections() {
      return editLayoutSections;
    }

    @Override
    public void setEditLayoutSections(com.sforce.soap.partner.IDescribeLayoutSection[] editLayoutSections) {
      this.editLayoutSections = castArray(com.sforce.soap.partner.DescribeLayoutSection.class, editLayoutSections);
      editLayoutSections__is_set = true;
    }

    /**
     * element : highlightsPanelLayoutSection of type {urn:partner.soap.sforce.com}DescribeLayoutSection
     * java type: com.sforce.soap.partner.DescribeLayoutSection
     */
    private static final com.sforce.ws.bind.TypeInfo highlightsPanelLayoutSection__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","highlightsPanelLayoutSection","urn:partner.soap.sforce.com","DescribeLayoutSection",0,1,true);

    private boolean highlightsPanelLayoutSection__is_set = false;

    private com.sforce.soap.partner.DescribeLayoutSection highlightsPanelLayoutSection;

    @Override
    public com.sforce.soap.partner.DescribeLayoutSection getHighlightsPanelLayoutSection() {
      return highlightsPanelLayoutSection;
    }

    @Override
    public void setHighlightsPanelLayoutSection(com.sforce.soap.partner.IDescribeLayoutSection highlightsPanelLayoutSection) {
      this.highlightsPanelLayoutSection = (com.sforce.soap.partner.DescribeLayoutSection)highlightsPanelLayoutSection;
      highlightsPanelLayoutSection__is_set = true;
    }

    /**
     * element : id of type {urn:partner.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo id__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","id","urn:partner.soap.sforce.com","ID",1,1,true);

    private boolean id__is_set = false;

    private java.lang.String id;

    @Override
    public java.lang.String getId() {
      return id;
    }

    @Override
    public void setId(java.lang.String id) {
      this.id = id;
      id__is_set = true;
    }

    /**
     * element : quickActionList of type {urn:partner.soap.sforce.com}DescribeQuickActionListResult
     * java type: com.sforce.soap.partner.DescribeQuickActionListResult
     */
    private static final com.sforce.ws.bind.TypeInfo quickActionList__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","quickActionList","urn:partner.soap.sforce.com","DescribeQuickActionListResult",0,1,true);

    private boolean quickActionList__is_set = false;

    private com.sforce.soap.partner.DescribeQuickActionListResult quickActionList;

    @Override
    public com.sforce.soap.partner.DescribeQuickActionListResult getQuickActionList() {
      return quickActionList;
    }

    @Override
    public void setQuickActionList(com.sforce.soap.partner.IDescribeQuickActionListResult quickActionList) {
      this.quickActionList = (com.sforce.soap.partner.DescribeQuickActionListResult)quickActionList;
      quickActionList__is_set = true;
    }

    /**
     * element : relatedContent of type {urn:partner.soap.sforce.com}RelatedContent
     * java type: com.sforce.soap.partner.RelatedContent
     */
    private static final com.sforce.ws.bind.TypeInfo relatedContent__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","relatedContent","urn:partner.soap.sforce.com","RelatedContent",0,1,true);

    private boolean relatedContent__is_set = false;

    private com.sforce.soap.partner.RelatedContent relatedContent;

    @Override
    public com.sforce.soap.partner.RelatedContent getRelatedContent() {
      return relatedContent;
    }

    @Override
    public void setRelatedContent(com.sforce.soap.partner.IRelatedContent relatedContent) {
      this.relatedContent = (com.sforce.soap.partner.RelatedContent)relatedContent;
      relatedContent__is_set = true;
    }

    /**
     * element : relatedLists of type {urn:partner.soap.sforce.com}RelatedList
     * java type: com.sforce.soap.partner.RelatedList[]
     */
    private static final com.sforce.ws.bind.TypeInfo relatedLists__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","relatedLists","urn:partner.soap.sforce.com","RelatedList",0,-1,true);

    private boolean relatedLists__is_set = false;

    private com.sforce.soap.partner.RelatedList[] relatedLists = new com.sforce.soap.partner.RelatedList[0];

    @Override
    public com.sforce.soap.partner.RelatedList[] getRelatedLists() {
      return relatedLists;
    }

    @Override
    public void setRelatedLists(com.sforce.soap.partner.IRelatedList[] relatedLists) {
      this.relatedLists = castArray(com.sforce.soap.partner.RelatedList.class, relatedLists);
      relatedLists__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, buttonLayoutSection__typeInfo, buttonLayoutSection, buttonLayoutSection__is_set);
       __typeMapper.writeObject(__out, detailLayoutSections__typeInfo, detailLayoutSections, detailLayoutSections__is_set);
       __typeMapper.writeObject(__out, editLayoutSections__typeInfo, editLayoutSections, editLayoutSections__is_set);
       __typeMapper.writeObject(__out, highlightsPanelLayoutSection__typeInfo, highlightsPanelLayoutSection, highlightsPanelLayoutSection__is_set);
       __typeMapper.writeString(__out, id__typeInfo, id, id__is_set);
       __typeMapper.writeObject(__out, quickActionList__typeInfo, quickActionList, quickActionList__is_set);
       __typeMapper.writeObject(__out, relatedContent__typeInfo, relatedContent, relatedContent__is_set);
       __typeMapper.writeObject(__out, relatedLists__typeInfo, relatedLists, relatedLists__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.isElement(__in, buttonLayoutSection__typeInfo)) {
            setButtonLayoutSection((com.sforce.soap.partner.DescribeLayoutButtonSection)__typeMapper.readObject(__in, buttonLayoutSection__typeInfo, com.sforce.soap.partner.DescribeLayoutButtonSection.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, detailLayoutSections__typeInfo)) {
            setDetailLayoutSections((com.sforce.soap.partner.DescribeLayoutSection[])__typeMapper.readObject(__in, detailLayoutSections__typeInfo, com.sforce.soap.partner.DescribeLayoutSection[].class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, editLayoutSections__typeInfo)) {
            setEditLayoutSections((com.sforce.soap.partner.DescribeLayoutSection[])__typeMapper.readObject(__in, editLayoutSections__typeInfo, com.sforce.soap.partner.DescribeLayoutSection[].class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, highlightsPanelLayoutSection__typeInfo)) {
            setHighlightsPanelLayoutSection((com.sforce.soap.partner.DescribeLayoutSection)__typeMapper.readObject(__in, highlightsPanelLayoutSection__typeInfo, com.sforce.soap.partner.DescribeLayoutSection.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, id__typeInfo)) {
            setId(__typeMapper.readString(__in, id__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, quickActionList__typeInfo)) {
            setQuickActionList((com.sforce.soap.partner.DescribeQuickActionListResult)__typeMapper.readObject(__in, quickActionList__typeInfo, com.sforce.soap.partner.DescribeQuickActionListResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, relatedContent__typeInfo)) {
            setRelatedContent((com.sforce.soap.partner.RelatedContent)__typeMapper.readObject(__in, relatedContent__typeInfo, com.sforce.soap.partner.RelatedContent.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, relatedLists__typeInfo)) {
            setRelatedLists((com.sforce.soap.partner.RelatedList[])__typeMapper.readObject(__in, relatedLists__typeInfo, com.sforce.soap.partner.RelatedList[].class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[DescribeLayout ");
      sb.append(" buttonLayoutSection='").append(com.sforce.ws.util.Verbose.toString(buttonLayoutSection)).append("'\n");
      sb.append(" detailLayoutSections='").append(com.sforce.ws.util.Verbose.toString(detailLayoutSections)).append("'\n");
      sb.append(" editLayoutSections='").append(com.sforce.ws.util.Verbose.toString(editLayoutSections)).append("'\n");
      sb.append(" highlightsPanelLayoutSection='").append(com.sforce.ws.util.Verbose.toString(highlightsPanelLayoutSection)).append("'\n");
      sb.append(" id='").append(com.sforce.ws.util.Verbose.toString(id)).append("'\n");
      sb.append(" quickActionList='").append(com.sforce.ws.util.Verbose.toString(quickActionList)).append("'\n");
      sb.append(" relatedContent='").append(com.sforce.ws.util.Verbose.toString(relatedContent)).append("'\n");
      sb.append(" relatedLists='").append(com.sforce.ws.util.Verbose.toString(relatedLists)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private <T,U> T[] castArray(Class<T> clazz, U[] array) {
        if (array == null) {
            return null;
        }
        T[] retVal = (T[]) java.lang.reflect.Array.newInstance(clazz, array.length);
        for (int i=0; i < array.length; i++) {
            retVal[i] = (T)array[i];
        }

        return retVal;
	}
}
