package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class Field implements com.sforce.ws.bind.XMLizable , IField{

    /**
     * Constructor
     */
    public Field() {}

    /**
     * element : autoNumber of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo autoNumber__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","autoNumber","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean autoNumber__is_set = false;

    private boolean autoNumber;

    @Override
    public boolean getAutoNumber() {
      return autoNumber;
    }

    @Override
    public boolean isAutoNumber() {
      return autoNumber;
    }

    @Override
    public void setAutoNumber(boolean autoNumber) {
      this.autoNumber = autoNumber;
      autoNumber__is_set = true;
    }

    /**
     * element : byteLength of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo byteLength__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","byteLength","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean byteLength__is_set = false;

    private int byteLength;

    @Override
    public int getByteLength() {
      return byteLength;
    }

    @Override
    public void setByteLength(int byteLength) {
      this.byteLength = byteLength;
      byteLength__is_set = true;
    }

    /**
     * element : calculated of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo calculated__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","calculated","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean calculated__is_set = false;

    private boolean calculated;

    @Override
    public boolean getCalculated() {
      return calculated;
    }

    @Override
    public boolean isCalculated() {
      return calculated;
    }

    @Override
    public void setCalculated(boolean calculated) {
      this.calculated = calculated;
      calculated__is_set = true;
    }

    /**
     * element : calculatedFormula of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo calculatedFormula__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","calculatedFormula","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean calculatedFormula__is_set = false;

    private java.lang.String calculatedFormula;

    @Override
    public java.lang.String getCalculatedFormula() {
      return calculatedFormula;
    }

    @Override
    public void setCalculatedFormula(java.lang.String calculatedFormula) {
      this.calculatedFormula = calculatedFormula;
      calculatedFormula__is_set = true;
    }

    /**
     * element : cascadeDelete of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo cascadeDelete__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","cascadeDelete","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean cascadeDelete__is_set = false;

    private boolean cascadeDelete;

    @Override
    public boolean getCascadeDelete() {
      return cascadeDelete;
    }

    @Override
    public boolean isCascadeDelete() {
      return cascadeDelete;
    }

    @Override
    public void setCascadeDelete(boolean cascadeDelete) {
      this.cascadeDelete = cascadeDelete;
      cascadeDelete__is_set = true;
    }

    /**
     * element : caseSensitive of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo caseSensitive__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","caseSensitive","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean caseSensitive__is_set = false;

    private boolean caseSensitive;

    @Override
    public boolean getCaseSensitive() {
      return caseSensitive;
    }

    @Override
    public boolean isCaseSensitive() {
      return caseSensitive;
    }

    @Override
    public void setCaseSensitive(boolean caseSensitive) {
      this.caseSensitive = caseSensitive;
      caseSensitive__is_set = true;
    }

    /**
     * element : controllerName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo controllerName__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","controllerName","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean controllerName__is_set = false;

    private java.lang.String controllerName;

    @Override
    public java.lang.String getControllerName() {
      return controllerName;
    }

    @Override
    public void setControllerName(java.lang.String controllerName) {
      this.controllerName = controllerName;
      controllerName__is_set = true;
    }

    /**
     * element : createable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo createable__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","createable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean createable__is_set = false;

    private boolean createable;

    @Override
    public boolean getCreateable() {
      return createable;
    }

    @Override
    public boolean isCreateable() {
      return createable;
    }

    @Override
    public void setCreateable(boolean createable) {
      this.createable = createable;
      createable__is_set = true;
    }

    /**
     * element : custom of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo custom__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","custom","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean custom__is_set = false;

    private boolean custom;

    @Override
    public boolean getCustom() {
      return custom;
    }

    @Override
    public boolean isCustom() {
      return custom;
    }

    @Override
    public void setCustom(boolean custom) {
      this.custom = custom;
      custom__is_set = true;
    }

    /**
     * element : defaultValueFormula of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo defaultValueFormula__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","defaultValueFormula","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean defaultValueFormula__is_set = false;

    private java.lang.String defaultValueFormula;

    @Override
    public java.lang.String getDefaultValueFormula() {
      return defaultValueFormula;
    }

    @Override
    public void setDefaultValueFormula(java.lang.String defaultValueFormula) {
      this.defaultValueFormula = defaultValueFormula;
      defaultValueFormula__is_set = true;
    }

    /**
     * element : defaultedOnCreate of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo defaultedOnCreate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","defaultedOnCreate","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean defaultedOnCreate__is_set = false;

    private boolean defaultedOnCreate;

    @Override
    public boolean getDefaultedOnCreate() {
      return defaultedOnCreate;
    }

    @Override
    public boolean isDefaultedOnCreate() {
      return defaultedOnCreate;
    }

    @Override
    public void setDefaultedOnCreate(boolean defaultedOnCreate) {
      this.defaultedOnCreate = defaultedOnCreate;
      defaultedOnCreate__is_set = true;
    }

    /**
     * element : dependentPicklist of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo dependentPicklist__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","dependentPicklist","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean dependentPicklist__is_set = false;

    private boolean dependentPicklist;

    @Override
    public boolean getDependentPicklist() {
      return dependentPicklist;
    }

    @Override
    public boolean isDependentPicklist() {
      return dependentPicklist;
    }

    @Override
    public void setDependentPicklist(boolean dependentPicklist) {
      this.dependentPicklist = dependentPicklist;
      dependentPicklist__is_set = true;
    }

    /**
     * element : deprecatedAndHidden of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo deprecatedAndHidden__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","deprecatedAndHidden","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean deprecatedAndHidden__is_set = false;

    private boolean deprecatedAndHidden;

    @Override
    public boolean getDeprecatedAndHidden() {
      return deprecatedAndHidden;
    }

    @Override
    public boolean isDeprecatedAndHidden() {
      return deprecatedAndHidden;
    }

    @Override
    public void setDeprecatedAndHidden(boolean deprecatedAndHidden) {
      this.deprecatedAndHidden = deprecatedAndHidden;
      deprecatedAndHidden__is_set = true;
    }

    /**
     * element : digits of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo digits__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","digits","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean digits__is_set = false;

    private int digits;

    @Override
    public int getDigits() {
      return digits;
    }

    @Override
    public void setDigits(int digits) {
      this.digits = digits;
      digits__is_set = true;
    }

    /**
     * element : displayLocationInDecimal of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo displayLocationInDecimal__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","displayLocationInDecimal","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean displayLocationInDecimal__is_set = false;

    private boolean displayLocationInDecimal;

    @Override
    public boolean getDisplayLocationInDecimal() {
      return displayLocationInDecimal;
    }

    @Override
    public boolean isDisplayLocationInDecimal() {
      return displayLocationInDecimal;
    }

    @Override
    public void setDisplayLocationInDecimal(boolean displayLocationInDecimal) {
      this.displayLocationInDecimal = displayLocationInDecimal;
      displayLocationInDecimal__is_set = true;
    }

    /**
     * element : externalId of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo externalId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","externalId","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean externalId__is_set = false;

    private boolean externalId;

    @Override
    public boolean getExternalId() {
      return externalId;
    }

    @Override
    public boolean isExternalId() {
      return externalId;
    }

    @Override
    public void setExternalId(boolean externalId) {
      this.externalId = externalId;
      externalId__is_set = true;
    }

    /**
     * element : extraTypeInfo of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo extraTypeInfo__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","extraTypeInfo","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean extraTypeInfo__is_set = false;

    private java.lang.String extraTypeInfo;

    @Override
    public java.lang.String getExtraTypeInfo() {
      return extraTypeInfo;
    }

    @Override
    public void setExtraTypeInfo(java.lang.String extraTypeInfo) {
      this.extraTypeInfo = extraTypeInfo;
      extraTypeInfo__is_set = true;
    }

    /**
     * element : filterable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo filterable__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","filterable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean filterable__is_set = false;

    private boolean filterable;

    @Override
    public boolean getFilterable() {
      return filterable;
    }

    @Override
    public boolean isFilterable() {
      return filterable;
    }

    @Override
    public void setFilterable(boolean filterable) {
      this.filterable = filterable;
      filterable__is_set = true;
    }

    /**
     * element : filteredLookupInfo of type {urn:partner.soap.sforce.com}FilteredLookupInfo
     * java type: com.sforce.soap.partner.FilteredLookupInfo
     */
    private static final com.sforce.ws.bind.TypeInfo filteredLookupInfo__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","filteredLookupInfo","urn:partner.soap.sforce.com","FilteredLookupInfo",0,1,true);

    private boolean filteredLookupInfo__is_set = false;

    private com.sforce.soap.partner.FilteredLookupInfo filteredLookupInfo;

    @Override
    public com.sforce.soap.partner.FilteredLookupInfo getFilteredLookupInfo() {
      return filteredLookupInfo;
    }

    @Override
    public void setFilteredLookupInfo(com.sforce.soap.partner.IFilteredLookupInfo filteredLookupInfo) {
      this.filteredLookupInfo = (com.sforce.soap.partner.FilteredLookupInfo)filteredLookupInfo;
      filteredLookupInfo__is_set = true;
    }

    /**
     * element : groupable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo groupable__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","groupable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean groupable__is_set = false;

    private boolean groupable;

    @Override
    public boolean getGroupable() {
      return groupable;
    }

    @Override
    public boolean isGroupable() {
      return groupable;
    }

    @Override
    public void setGroupable(boolean groupable) {
      this.groupable = groupable;
      groupable__is_set = true;
    }

    /**
     * element : highScaleNumber of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo highScaleNumber__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","highScaleNumber","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean highScaleNumber__is_set = false;

    private boolean highScaleNumber;

    @Override
    public boolean getHighScaleNumber() {
      return highScaleNumber;
    }

    @Override
    public boolean isHighScaleNumber() {
      return highScaleNumber;
    }

    @Override
    public void setHighScaleNumber(boolean highScaleNumber) {
      this.highScaleNumber = highScaleNumber;
      highScaleNumber__is_set = true;
    }

    /**
     * element : htmlFormatted of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo htmlFormatted__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","htmlFormatted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean htmlFormatted__is_set = false;

    private boolean htmlFormatted;

    @Override
    public boolean getHtmlFormatted() {
      return htmlFormatted;
    }

    @Override
    public boolean isHtmlFormatted() {
      return htmlFormatted;
    }

    @Override
    public void setHtmlFormatted(boolean htmlFormatted) {
      this.htmlFormatted = htmlFormatted;
      htmlFormatted__is_set = true;
    }

    /**
     * element : idLookup of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo idLookup__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","idLookup","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean idLookup__is_set = false;

    private boolean idLookup;

    @Override
    public boolean getIdLookup() {
      return idLookup;
    }

    @Override
    public boolean isIdLookup() {
      return idLookup;
    }

    @Override
    public void setIdLookup(boolean idLookup) {
      this.idLookup = idLookup;
      idLookup__is_set = true;
    }

    /**
     * element : inlineHelpText of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo inlineHelpText__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","inlineHelpText","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean inlineHelpText__is_set = false;

    private java.lang.String inlineHelpText;

    @Override
    public java.lang.String getInlineHelpText() {
      return inlineHelpText;
    }

    @Override
    public void setInlineHelpText(java.lang.String inlineHelpText) {
      this.inlineHelpText = inlineHelpText;
      inlineHelpText__is_set = true;
    }

    /**
     * element : label of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo label__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","label","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean label__is_set = false;

    private java.lang.String label;

    @Override
    public java.lang.String getLabel() {
      return label;
    }

    @Override
    public void setLabel(java.lang.String label) {
      this.label = label;
      label__is_set = true;
    }

    /**
     * element : length of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo length__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","length","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean length__is_set = false;

    private int length;

    @Override
    public int getLength() {
      return length;
    }

    @Override
    public void setLength(int length) {
      this.length = length;
      length__is_set = true;
    }

    /**
     * element : mask of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo mask__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","mask","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean mask__is_set = false;

    private java.lang.String mask;

    @Override
    public java.lang.String getMask() {
      return mask;
    }

    @Override
    public void setMask(java.lang.String mask) {
      this.mask = mask;
      mask__is_set = true;
    }

    /**
     * element : maskType of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo maskType__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","maskType","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean maskType__is_set = false;

    private java.lang.String maskType;

    @Override
    public java.lang.String getMaskType() {
      return maskType;
    }

    @Override
    public void setMaskType(java.lang.String maskType) {
      this.maskType = maskType;
      maskType__is_set = true;
    }

    /**
     * element : name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo name__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","name","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean name__is_set = false;

    private java.lang.String name;

    @Override
    public java.lang.String getName() {
      return name;
    }

    @Override
    public void setName(java.lang.String name) {
      this.name = name;
      name__is_set = true;
    }

    /**
     * element : nameField of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo nameField__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","nameField","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean nameField__is_set = false;

    private boolean nameField;

    @Override
    public boolean getNameField() {
      return nameField;
    }

    @Override
    public boolean isNameField() {
      return nameField;
    }

    @Override
    public void setNameField(boolean nameField) {
      this.nameField = nameField;
      nameField__is_set = true;
    }

    /**
     * element : namePointing of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo namePointing__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","namePointing","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean namePointing__is_set = false;

    private boolean namePointing;

    @Override
    public boolean getNamePointing() {
      return namePointing;
    }

    @Override
    public boolean isNamePointing() {
      return namePointing;
    }

    @Override
    public void setNamePointing(boolean namePointing) {
      this.namePointing = namePointing;
      namePointing__is_set = true;
    }

    /**
     * element : nillable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo nillable__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","nillable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean nillable__is_set = false;

    private boolean nillable;

    @Override
    public boolean getNillable() {
      return nillable;
    }

    @Override
    public boolean isNillable() {
      return nillable;
    }

    @Override
    public void setNillable(boolean nillable) {
      this.nillable = nillable;
      nillable__is_set = true;
    }

    /**
     * element : permissionable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo permissionable__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","permissionable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean permissionable__is_set = false;

    private boolean permissionable;

    @Override
    public boolean getPermissionable() {
      return permissionable;
    }

    @Override
    public boolean isPermissionable() {
      return permissionable;
    }

    @Override
    public void setPermissionable(boolean permissionable) {
      this.permissionable = permissionable;
      permissionable__is_set = true;
    }

    /**
     * element : picklistValues of type {urn:partner.soap.sforce.com}PicklistEntry
     * java type: com.sforce.soap.partner.PicklistEntry[]
     */
    private static final com.sforce.ws.bind.TypeInfo picklistValues__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","picklistValues","urn:partner.soap.sforce.com","PicklistEntry",0,-1,true);

    private boolean picklistValues__is_set = false;

    private com.sforce.soap.partner.PicklistEntry[] picklistValues = new com.sforce.soap.partner.PicklistEntry[0];

    @Override
    public com.sforce.soap.partner.PicklistEntry[] getPicklistValues() {
      return picklistValues;
    }

    @Override
    public void setPicklistValues(com.sforce.soap.partner.IPicklistEntry[] picklistValues) {
      this.picklistValues = castArray(com.sforce.soap.partner.PicklistEntry.class, picklistValues);
      picklistValues__is_set = true;
    }

    /**
     * element : precision of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo precision__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","precision","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean precision__is_set = false;

    private int precision;

    @Override
    public int getPrecision() {
      return precision;
    }

    @Override
    public void setPrecision(int precision) {
      this.precision = precision;
      precision__is_set = true;
    }

    /**
     * element : queryByDistance of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo queryByDistance__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","queryByDistance","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean queryByDistance__is_set = false;

    private boolean queryByDistance;

    @Override
    public boolean getQueryByDistance() {
      return queryByDistance;
    }

    @Override
    public boolean isQueryByDistance() {
      return queryByDistance;
    }

    @Override
    public void setQueryByDistance(boolean queryByDistance) {
      this.queryByDistance = queryByDistance;
      queryByDistance__is_set = true;
    }

    /**
     * element : referenceTargetField of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo referenceTargetField__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","referenceTargetField","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean referenceTargetField__is_set = false;

    private java.lang.String referenceTargetField;

    @Override
    public java.lang.String getReferenceTargetField() {
      return referenceTargetField;
    }

    @Override
    public void setReferenceTargetField(java.lang.String referenceTargetField) {
      this.referenceTargetField = referenceTargetField;
      referenceTargetField__is_set = true;
    }

    /**
     * element : referenceTo of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String[]
     */
    private static final com.sforce.ws.bind.TypeInfo referenceTo__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","referenceTo","http://www.w3.org/2001/XMLSchema","string",0,-1,true);

    private boolean referenceTo__is_set = false;

    private java.lang.String[] referenceTo = new java.lang.String[0];

    @Override
    public java.lang.String[] getReferenceTo() {
      return referenceTo;
    }

    @Override
    public void setReferenceTo(java.lang.String[] referenceTo) {
      this.referenceTo = castArray(java.lang.String.class, referenceTo);
      referenceTo__is_set = true;
    }

    /**
     * element : relationshipName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo relationshipName__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","relationshipName","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean relationshipName__is_set = false;

    private java.lang.String relationshipName;

    @Override
    public java.lang.String getRelationshipName() {
      return relationshipName;
    }

    @Override
    public void setRelationshipName(java.lang.String relationshipName) {
      this.relationshipName = relationshipName;
      relationshipName__is_set = true;
    }

    /**
     * element : relationshipOrder of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo relationshipOrder__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","relationshipOrder","http://www.w3.org/2001/XMLSchema","int",0,1,true);

    private boolean relationshipOrder__is_set = false;

    private int relationshipOrder;

    @Override
    public int getRelationshipOrder() {
      return relationshipOrder;
    }

    @Override
    public void setRelationshipOrder(int relationshipOrder) {
      this.relationshipOrder = relationshipOrder;
      relationshipOrder__is_set = true;
    }

    /**
     * element : restrictedDelete of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo restrictedDelete__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","restrictedDelete","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean restrictedDelete__is_set = false;

    private boolean restrictedDelete;

    @Override
    public boolean getRestrictedDelete() {
      return restrictedDelete;
    }

    @Override
    public boolean isRestrictedDelete() {
      return restrictedDelete;
    }

    @Override
    public void setRestrictedDelete(boolean restrictedDelete) {
      this.restrictedDelete = restrictedDelete;
      restrictedDelete__is_set = true;
    }

    /**
     * element : restrictedPicklist of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo restrictedPicklist__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","restrictedPicklist","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean restrictedPicklist__is_set = false;

    private boolean restrictedPicklist;

    @Override
    public boolean getRestrictedPicklist() {
      return restrictedPicklist;
    }

    @Override
    public boolean isRestrictedPicklist() {
      return restrictedPicklist;
    }

    @Override
    public void setRestrictedPicklist(boolean restrictedPicklist) {
      this.restrictedPicklist = restrictedPicklist;
      restrictedPicklist__is_set = true;
    }

    /**
     * element : scale of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo scale__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","scale","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean scale__is_set = false;

    private int scale;

    @Override
    public int getScale() {
      return scale;
    }

    @Override
    public void setScale(int scale) {
      this.scale = scale;
      scale__is_set = true;
    }

    /**
     * element : soapType of type {urn:partner.soap.sforce.com}soapType
     * java type: com.sforce.soap.partner.SoapType
     */
    private static final com.sforce.ws.bind.TypeInfo soapType__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","soapType","urn:partner.soap.sforce.com","soapType",1,1,true);

    private boolean soapType__is_set = false;

    private com.sforce.soap.partner.SoapType soapType;

    @Override
    public com.sforce.soap.partner.SoapType getSoapType() {
      return soapType;
    }

    @Override
    public void setSoapType(com.sforce.soap.partner.SoapType soapType) {
      this.soapType = soapType;
      soapType__is_set = true;
    }

    /**
     * element : sortable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo sortable__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","sortable","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean sortable__is_set = false;

    private boolean sortable;

    @Override
    public boolean getSortable() {
      return sortable;
    }

    @Override
    public boolean isSortable() {
      return sortable;
    }

    @Override
    public void setSortable(boolean sortable) {
      this.sortable = sortable;
      sortable__is_set = true;
    }

    /**
     * element : type of type {urn:partner.soap.sforce.com}fieldType
     * java type: com.sforce.soap.partner.FieldType
     */
    private static final com.sforce.ws.bind.TypeInfo type__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","type","urn:partner.soap.sforce.com","fieldType",1,1,true);

    private boolean type__is_set = false;

    private com.sforce.soap.partner.FieldType type;

    @Override
    public com.sforce.soap.partner.FieldType getType() {
      return type;
    }

    @Override
    public void setType(com.sforce.soap.partner.FieldType type) {
      this.type = type;
      type__is_set = true;
    }

    /**
     * element : unique of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo unique__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","unique","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean unique__is_set = false;

    private boolean unique;

    @Override
    public boolean getUnique() {
      return unique;
    }

    @Override
    public boolean isUnique() {
      return unique;
    }

    @Override
    public void setUnique(boolean unique) {
      this.unique = unique;
      unique__is_set = true;
    }

    /**
     * element : updateable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo updateable__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","updateable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean updateable__is_set = false;

    private boolean updateable;

    @Override
    public boolean getUpdateable() {
      return updateable;
    }

    @Override
    public boolean isUpdateable() {
      return updateable;
    }

    @Override
    public void setUpdateable(boolean updateable) {
      this.updateable = updateable;
      updateable__is_set = true;
    }

    /**
     * element : writeRequiresMasterRead of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo writeRequiresMasterRead__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","writeRequiresMasterRead","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean writeRequiresMasterRead__is_set = false;

    private boolean writeRequiresMasterRead;

    @Override
    public boolean getWriteRequiresMasterRead() {
      return writeRequiresMasterRead;
    }

    @Override
    public boolean isWriteRequiresMasterRead() {
      return writeRequiresMasterRead;
    }

    @Override
    public void setWriteRequiresMasterRead(boolean writeRequiresMasterRead) {
      this.writeRequiresMasterRead = writeRequiresMasterRead;
      writeRequiresMasterRead__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeBoolean(__out, autoNumber__typeInfo, autoNumber, autoNumber__is_set);
       __typeMapper.writeInt(__out, byteLength__typeInfo, byteLength, byteLength__is_set);
       __typeMapper.writeBoolean(__out, calculated__typeInfo, calculated, calculated__is_set);
       __typeMapper.writeString(__out, calculatedFormula__typeInfo, calculatedFormula, calculatedFormula__is_set);
       __typeMapper.writeBoolean(__out, cascadeDelete__typeInfo, cascadeDelete, cascadeDelete__is_set);
       __typeMapper.writeBoolean(__out, caseSensitive__typeInfo, caseSensitive, caseSensitive__is_set);
       __typeMapper.writeString(__out, controllerName__typeInfo, controllerName, controllerName__is_set);
       __typeMapper.writeBoolean(__out, createable__typeInfo, createable, createable__is_set);
       __typeMapper.writeBoolean(__out, custom__typeInfo, custom, custom__is_set);
       __typeMapper.writeString(__out, defaultValueFormula__typeInfo, defaultValueFormula, defaultValueFormula__is_set);
       __typeMapper.writeBoolean(__out, defaultedOnCreate__typeInfo, defaultedOnCreate, defaultedOnCreate__is_set);
       __typeMapper.writeBoolean(__out, dependentPicklist__typeInfo, dependentPicklist, dependentPicklist__is_set);
       __typeMapper.writeBoolean(__out, deprecatedAndHidden__typeInfo, deprecatedAndHidden, deprecatedAndHidden__is_set);
       __typeMapper.writeInt(__out, digits__typeInfo, digits, digits__is_set);
       __typeMapper.writeBoolean(__out, displayLocationInDecimal__typeInfo, displayLocationInDecimal, displayLocationInDecimal__is_set);
       __typeMapper.writeBoolean(__out, externalId__typeInfo, externalId, externalId__is_set);
       __typeMapper.writeString(__out, extraTypeInfo__typeInfo, extraTypeInfo, extraTypeInfo__is_set);
       __typeMapper.writeBoolean(__out, filterable__typeInfo, filterable, filterable__is_set);
       __typeMapper.writeObject(__out, filteredLookupInfo__typeInfo, filteredLookupInfo, filteredLookupInfo__is_set);
       __typeMapper.writeBoolean(__out, groupable__typeInfo, groupable, groupable__is_set);
       __typeMapper.writeBoolean(__out, highScaleNumber__typeInfo, highScaleNumber, highScaleNumber__is_set);
       __typeMapper.writeBoolean(__out, htmlFormatted__typeInfo, htmlFormatted, htmlFormatted__is_set);
       __typeMapper.writeBoolean(__out, idLookup__typeInfo, idLookup, idLookup__is_set);
       __typeMapper.writeString(__out, inlineHelpText__typeInfo, inlineHelpText, inlineHelpText__is_set);
       __typeMapper.writeString(__out, label__typeInfo, label, label__is_set);
       __typeMapper.writeInt(__out, length__typeInfo, length, length__is_set);
       __typeMapper.writeString(__out, mask__typeInfo, mask, mask__is_set);
       __typeMapper.writeString(__out, maskType__typeInfo, maskType, maskType__is_set);
       __typeMapper.writeString(__out, name__typeInfo, name, name__is_set);
       __typeMapper.writeBoolean(__out, nameField__typeInfo, nameField, nameField__is_set);
       __typeMapper.writeBoolean(__out, namePointing__typeInfo, namePointing, namePointing__is_set);
       __typeMapper.writeBoolean(__out, nillable__typeInfo, nillable, nillable__is_set);
       __typeMapper.writeBoolean(__out, permissionable__typeInfo, permissionable, permissionable__is_set);
       __typeMapper.writeObject(__out, picklistValues__typeInfo, picklistValues, picklistValues__is_set);
       __typeMapper.writeInt(__out, precision__typeInfo, precision, precision__is_set);
       __typeMapper.writeBoolean(__out, queryByDistance__typeInfo, queryByDistance, queryByDistance__is_set);
       __typeMapper.writeString(__out, referenceTargetField__typeInfo, referenceTargetField, referenceTargetField__is_set);
       __typeMapper.writeObject(__out, referenceTo__typeInfo, referenceTo, referenceTo__is_set);
       __typeMapper.writeString(__out, relationshipName__typeInfo, relationshipName, relationshipName__is_set);
       __typeMapper.writeInt(__out, relationshipOrder__typeInfo, relationshipOrder, relationshipOrder__is_set);
       __typeMapper.writeBoolean(__out, restrictedDelete__typeInfo, restrictedDelete, restrictedDelete__is_set);
       __typeMapper.writeBoolean(__out, restrictedPicklist__typeInfo, restrictedPicklist, restrictedPicklist__is_set);
       __typeMapper.writeInt(__out, scale__typeInfo, scale, scale__is_set);
       __typeMapper.writeObject(__out, soapType__typeInfo, soapType, soapType__is_set);
       __typeMapper.writeBoolean(__out, sortable__typeInfo, sortable, sortable__is_set);
       __typeMapper.writeObject(__out, type__typeInfo, type, type__is_set);
       __typeMapper.writeBoolean(__out, unique__typeInfo, unique, unique__is_set);
       __typeMapper.writeBoolean(__out, updateable__typeInfo, updateable, updateable__is_set);
       __typeMapper.writeBoolean(__out, writeRequiresMasterRead__typeInfo, writeRequiresMasterRead, writeRequiresMasterRead__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, autoNumber__typeInfo)) {
            setAutoNumber(__typeMapper.readBoolean(__in, autoNumber__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, byteLength__typeInfo)) {
            setByteLength((int)__typeMapper.readInt(__in, byteLength__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, calculated__typeInfo)) {
            setCalculated(__typeMapper.readBoolean(__in, calculated__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, calculatedFormula__typeInfo)) {
            setCalculatedFormula(__typeMapper.readString(__in, calculatedFormula__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, cascadeDelete__typeInfo)) {
            setCascadeDelete(__typeMapper.readBoolean(__in, cascadeDelete__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, caseSensitive__typeInfo)) {
            setCaseSensitive(__typeMapper.readBoolean(__in, caseSensitive__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, controllerName__typeInfo)) {
            setControllerName(__typeMapper.readString(__in, controllerName__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, createable__typeInfo)) {
            setCreateable(__typeMapper.readBoolean(__in, createable__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, custom__typeInfo)) {
            setCustom(__typeMapper.readBoolean(__in, custom__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, defaultValueFormula__typeInfo)) {
            setDefaultValueFormula(__typeMapper.readString(__in, defaultValueFormula__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, defaultedOnCreate__typeInfo)) {
            setDefaultedOnCreate(__typeMapper.readBoolean(__in, defaultedOnCreate__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, dependentPicklist__typeInfo)) {
            setDependentPicklist(__typeMapper.readBoolean(__in, dependentPicklist__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, deprecatedAndHidden__typeInfo)) {
            setDeprecatedAndHidden(__typeMapper.readBoolean(__in, deprecatedAndHidden__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, digits__typeInfo)) {
            setDigits((int)__typeMapper.readInt(__in, digits__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, displayLocationInDecimal__typeInfo)) {
            setDisplayLocationInDecimal(__typeMapper.readBoolean(__in, displayLocationInDecimal__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, externalId__typeInfo)) {
            setExternalId(__typeMapper.readBoolean(__in, externalId__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, extraTypeInfo__typeInfo)) {
            setExtraTypeInfo(__typeMapper.readString(__in, extraTypeInfo__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, filterable__typeInfo)) {
            setFilterable(__typeMapper.readBoolean(__in, filterable__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, filteredLookupInfo__typeInfo)) {
            setFilteredLookupInfo((com.sforce.soap.partner.FilteredLookupInfo)__typeMapper.readObject(__in, filteredLookupInfo__typeInfo, com.sforce.soap.partner.FilteredLookupInfo.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, groupable__typeInfo)) {
            setGroupable(__typeMapper.readBoolean(__in, groupable__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, highScaleNumber__typeInfo)) {
            setHighScaleNumber(__typeMapper.readBoolean(__in, highScaleNumber__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, htmlFormatted__typeInfo)) {
            setHtmlFormatted(__typeMapper.readBoolean(__in, htmlFormatted__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, idLookup__typeInfo)) {
            setIdLookup(__typeMapper.readBoolean(__in, idLookup__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, inlineHelpText__typeInfo)) {
            setInlineHelpText(__typeMapper.readString(__in, inlineHelpText__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, label__typeInfo)) {
            setLabel(__typeMapper.readString(__in, label__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, length__typeInfo)) {
            setLength((int)__typeMapper.readInt(__in, length__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, mask__typeInfo)) {
            setMask(__typeMapper.readString(__in, mask__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, maskType__typeInfo)) {
            setMaskType(__typeMapper.readString(__in, maskType__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, name__typeInfo)) {
            setName(__typeMapper.readString(__in, name__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, nameField__typeInfo)) {
            setNameField(__typeMapper.readBoolean(__in, nameField__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, namePointing__typeInfo)) {
            setNamePointing(__typeMapper.readBoolean(__in, namePointing__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, nillable__typeInfo)) {
            setNillable(__typeMapper.readBoolean(__in, nillable__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, permissionable__typeInfo)) {
            setPermissionable(__typeMapper.readBoolean(__in, permissionable__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, picklistValues__typeInfo)) {
            setPicklistValues((com.sforce.soap.partner.PicklistEntry[])__typeMapper.readObject(__in, picklistValues__typeInfo, com.sforce.soap.partner.PicklistEntry[].class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, precision__typeInfo)) {
            setPrecision((int)__typeMapper.readInt(__in, precision__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, queryByDistance__typeInfo)) {
            setQueryByDistance(__typeMapper.readBoolean(__in, queryByDistance__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, referenceTargetField__typeInfo)) {
            setReferenceTargetField(__typeMapper.readString(__in, referenceTargetField__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, referenceTo__typeInfo)) {
            setReferenceTo((java.lang.String[])__typeMapper.readObject(__in, referenceTo__typeInfo, java.lang.String[].class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, relationshipName__typeInfo)) {
            setRelationshipName(__typeMapper.readString(__in, relationshipName__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, relationshipOrder__typeInfo)) {
            setRelationshipOrder((int)__typeMapper.readInt(__in, relationshipOrder__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, restrictedDelete__typeInfo)) {
            setRestrictedDelete(__typeMapper.readBoolean(__in, restrictedDelete__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, restrictedPicklist__typeInfo)) {
            setRestrictedPicklist(__typeMapper.readBoolean(__in, restrictedPicklist__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, scale__typeInfo)) {
            setScale((int)__typeMapper.readInt(__in, scale__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, soapType__typeInfo)) {
            setSoapType((com.sforce.soap.partner.SoapType)__typeMapper.readObject(__in, soapType__typeInfo, com.sforce.soap.partner.SoapType.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, sortable__typeInfo)) {
            setSortable(__typeMapper.readBoolean(__in, sortable__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, type__typeInfo)) {
            setType((com.sforce.soap.partner.FieldType)__typeMapper.readObject(__in, type__typeInfo, com.sforce.soap.partner.FieldType.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, unique__typeInfo)) {
            setUnique(__typeMapper.readBoolean(__in, unique__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, updateable__typeInfo)) {
            setUpdateable(__typeMapper.readBoolean(__in, updateable__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, writeRequiresMasterRead__typeInfo)) {
            setWriteRequiresMasterRead(__typeMapper.readBoolean(__in, writeRequiresMasterRead__typeInfo, boolean.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[Field ");
      sb.append(" autoNumber='").append(com.sforce.ws.util.Verbose.toString(autoNumber)).append("'\n");
      sb.append(" byteLength='").append(com.sforce.ws.util.Verbose.toString(byteLength)).append("'\n");
      sb.append(" calculated='").append(com.sforce.ws.util.Verbose.toString(calculated)).append("'\n");
      sb.append(" calculatedFormula='").append(com.sforce.ws.util.Verbose.toString(calculatedFormula)).append("'\n");
      sb.append(" cascadeDelete='").append(com.sforce.ws.util.Verbose.toString(cascadeDelete)).append("'\n");
      sb.append(" caseSensitive='").append(com.sforce.ws.util.Verbose.toString(caseSensitive)).append("'\n");
      sb.append(" controllerName='").append(com.sforce.ws.util.Verbose.toString(controllerName)).append("'\n");
      sb.append(" createable='").append(com.sforce.ws.util.Verbose.toString(createable)).append("'\n");
      sb.append(" custom='").append(com.sforce.ws.util.Verbose.toString(custom)).append("'\n");
      sb.append(" defaultValueFormula='").append(com.sforce.ws.util.Verbose.toString(defaultValueFormula)).append("'\n");
      sb.append(" defaultedOnCreate='").append(com.sforce.ws.util.Verbose.toString(defaultedOnCreate)).append("'\n");
      sb.append(" dependentPicklist='").append(com.sforce.ws.util.Verbose.toString(dependentPicklist)).append("'\n");
      sb.append(" deprecatedAndHidden='").append(com.sforce.ws.util.Verbose.toString(deprecatedAndHidden)).append("'\n");
      sb.append(" digits='").append(com.sforce.ws.util.Verbose.toString(digits)).append("'\n");
      sb.append(" displayLocationInDecimal='").append(com.sforce.ws.util.Verbose.toString(displayLocationInDecimal)).append("'\n");
      sb.append(" externalId='").append(com.sforce.ws.util.Verbose.toString(externalId)).append("'\n");
      sb.append(" extraTypeInfo='").append(com.sforce.ws.util.Verbose.toString(extraTypeInfo)).append("'\n");
      sb.append(" filterable='").append(com.sforce.ws.util.Verbose.toString(filterable)).append("'\n");
      sb.append(" filteredLookupInfo='").append(com.sforce.ws.util.Verbose.toString(filteredLookupInfo)).append("'\n");
      sb.append(" groupable='").append(com.sforce.ws.util.Verbose.toString(groupable)).append("'\n");
      sb.append(" highScaleNumber='").append(com.sforce.ws.util.Verbose.toString(highScaleNumber)).append("'\n");
      sb.append(" htmlFormatted='").append(com.sforce.ws.util.Verbose.toString(htmlFormatted)).append("'\n");
      sb.append(" idLookup='").append(com.sforce.ws.util.Verbose.toString(idLookup)).append("'\n");
      sb.append(" inlineHelpText='").append(com.sforce.ws.util.Verbose.toString(inlineHelpText)).append("'\n");
      sb.append(" label='").append(com.sforce.ws.util.Verbose.toString(label)).append("'\n");
      sb.append(" length='").append(com.sforce.ws.util.Verbose.toString(length)).append("'\n");
      sb.append(" mask='").append(com.sforce.ws.util.Verbose.toString(mask)).append("'\n");
      sb.append(" maskType='").append(com.sforce.ws.util.Verbose.toString(maskType)).append("'\n");
      sb.append(" name='").append(com.sforce.ws.util.Verbose.toString(name)).append("'\n");
      sb.append(" nameField='").append(com.sforce.ws.util.Verbose.toString(nameField)).append("'\n");
      sb.append(" namePointing='").append(com.sforce.ws.util.Verbose.toString(namePointing)).append("'\n");
      sb.append(" nillable='").append(com.sforce.ws.util.Verbose.toString(nillable)).append("'\n");
      sb.append(" permissionable='").append(com.sforce.ws.util.Verbose.toString(permissionable)).append("'\n");
      sb.append(" picklistValues='").append(com.sforce.ws.util.Verbose.toString(picklistValues)).append("'\n");
      sb.append(" precision='").append(com.sforce.ws.util.Verbose.toString(precision)).append("'\n");
      sb.append(" queryByDistance='").append(com.sforce.ws.util.Verbose.toString(queryByDistance)).append("'\n");
      sb.append(" referenceTargetField='").append(com.sforce.ws.util.Verbose.toString(referenceTargetField)).append("'\n");
      sb.append(" referenceTo='").append(com.sforce.ws.util.Verbose.toString(referenceTo)).append("'\n");
      sb.append(" relationshipName='").append(com.sforce.ws.util.Verbose.toString(relationshipName)).append("'\n");
      sb.append(" relationshipOrder='").append(com.sforce.ws.util.Verbose.toString(relationshipOrder)).append("'\n");
      sb.append(" restrictedDelete='").append(com.sforce.ws.util.Verbose.toString(restrictedDelete)).append("'\n");
      sb.append(" restrictedPicklist='").append(com.sforce.ws.util.Verbose.toString(restrictedPicklist)).append("'\n");
      sb.append(" scale='").append(com.sforce.ws.util.Verbose.toString(scale)).append("'\n");
      sb.append(" soapType='").append(com.sforce.ws.util.Verbose.toString(soapType)).append("'\n");
      sb.append(" sortable='").append(com.sforce.ws.util.Verbose.toString(sortable)).append("'\n");
      sb.append(" type='").append(com.sforce.ws.util.Verbose.toString(type)).append("'\n");
      sb.append(" unique='").append(com.sforce.ws.util.Verbose.toString(unique)).append("'\n");
      sb.append(" updateable='").append(com.sforce.ws.util.Verbose.toString(updateable)).append("'\n");
      sb.append(" writeRequiresMasterRead='").append(com.sforce.ws.util.Verbose.toString(writeRequiresMasterRead)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private <T,U> T[] castArray(Class<T> clazz, U[] array) {
        if (array == null) {
            return null;
        }
        T[] retVal = (T[]) java.lang.reflect.Array.newInstance(clazz, array.length);
        for (int i=0; i < array.length; i++) {
            retVal[i] = (T)array[i];
        }

        return retVal;
	}
}
