package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IGetUpdatedResult  {

      /**
       * element : ids of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String[]
       */

      public java.lang.String[] getIds();

      public void setIds(java.lang.String[] ids);

      /**
       * element : latestDateCovered of type {http://www.w3.org/2001/XMLSchema}dateTime
       * java type: java.util.Calendar
       */

      public java.util.Calendar getLatestDateCovered();

      public void setLatestDateCovered(java.util.Calendar latestDateCovered);

      /**
       * element : sforceReserved of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getSforceReserved();

      public void setSforceReserved(java.lang.String sforceReserved);


}
